=== genestack/user-docs/docs/tools/odm-sdk/terminal/templates/template_schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "title": "JSON schema for metainfo templates",
  "description": "This schema is used to validate metainfo templates upon upload",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "name": {
        "description": "Key name",
        "type": "string"
      },
      "description": {
        "description": "Key description",
        "type": "string",
        "maxLength": 500
      },
      "isRequired": {
        "type": "boolean"
      },
      "isSingle": {
        "description": "Deprecated",
        "type": "boolean"
      },
      "isReadOnly": {
        "description": "If the value of this key cannot be edited",
        "type": "boolean"
      },
      "metainfoType": {
        "type": "string",
        "enum": [
          "com.genestack.api.metainfo.IntegerValue",
          "com.genestack.api.metainfo.DecimalValue",
          "com.genestack.api.metainfo.StringValue",
          "com.genestack.api.metainfo.BooleanValue",
          "com.genestack.api.metainfo.DateTimeValue",
          "com.genestack.api.metainfo.ExternalLink"
        ]
      },
      "dataType": {
        "description": "Data type name to which this key is applicable",
        "type": "string",
        "enum": [
          "study",
          "genestack:sampleObject",
          "genestack:libraryObject",
          "genestack:preparationObject",
          "genestack:facsParent",
          "genestack:genomicsParent",
          "genestack:transcriptomicsParent"
        ]
      },
      "dictionaryName": {
        "description": "Name of the dictionary which should already be loaded and shared in ODM",
        "type": "string"
      }
    },
    "required": [
      "name",
      "isRequired",
      "metainfoType",
      "dataType"
    ],
    "dependencies": {
      "dictionaryPath": [
        "dictionaryName"
      ]
    },
    "additionalProperties": false
  },
  "uniqueItems": true
}

=== genestack/user-docs/docs/tools/odm-sdk/terminal/templates/Default_ODM_Template.json
[
  {
    "dataType": "study",
    "isRequired": true,
    "metainfoType": "com.genestack.api.metainfo.StringValue",
    "name": "Study Source",
    "isReadOnly": false
  },
  {
    "dataType": "study",
    "isRequired": true,
    "metainfoType": "com.genestack.api.metainfo.StringValue",
    "name": "Study Source ID",
    "isReadOnly": false
  },
  {
    "dataType": "study",
    "isRequired": true,
    "metainfoType": "com.genestack.api.metainfo.StringValue",
    "name": "Study Description",
    "isReadOnly": false,
    "description": "Hypothesis, abstract - enough to understand what the study is about"
  },
  {
    "dataType": "study",
    "isRequired": false,
    "metainfoType": "com.genestack.api.metainfo.StringValue",
    "name": "Study Type",
    "isReadOnly": false
  },
  {
    "dataType": "study",
    "isRequired": false,
    "metainfoType": "com.genestack.api.metainfo.StringValue",
    "name": "Study Design",
    "isReadOnly": false
  },
  {
    "dataType": "study",
    "isRequired": false,
    "metainfoType": "com.genestack.api.metainfo.StringValue",
    "name": "Therapeutic Area",
    "isReadOnly": false,
    "dictionaryName": "Therapeutic Area",
    "description": "Name of the TA"
  },
  {
    "dataType": "study",
    "isRequired": false,
    "metainfoType": "com.genestack.api.metainfo.StringValue",
    "name": "Contributor",
    "isReadOnly": false
  },
  {
    "dataType": "study",
    "isRequired": false,
    "metainfoType": "com.genestack.api.metainfo.StringValue",
    "name": "Contributor Email",
    "isReadOnly": false
  },
  {
    "dataType": "study",
    "isRequired": false,
    "metainfoType": "com.genestack.api.metainfo.DateTimeValue",
    "name": "Release Date",
    "isReadOnly": false
  },
  {
    "dataType": "study",
    "isRequired": false,
    "metainfoType": "com.genestack.api.metainfo.DateTimeValue",
    "name": "Last Update Date",
    "isReadOnly": false
  },
  {
    "dataType": "study",
    "isRequired": false,
    "metainfoType": "com.genestack.api.metainfo.ExternalLink",
    "name": "Import Source URL",
    "isReadOnly": false
  },
  {
    "dictionaryName": "Sequencing Platforms",
    "dataType": "genestack:transcriptomicsParent",
    "isRequired": false,
    "metainfoType": "com.genestack.api.metainfo.StringValue",
    "name": "Experimental Platform",
    "isReadOnly": false
  },
  {
    "dataType": "genestack:transcriptomicsParent",
    "isRequired": false,
    "metainfoType": "com.genestack.api.metainfo.StringValue",
    "name": "Data Processing Method",
    "isReadOnly": false
  },
  {
    "dataType": "genestack:transcriptomicsParent",
    "isRequired": false,
    "metainfoType": "com.genestack.api.metainfo.StringValue",
    "name": "Scale",
    "isReadOnly": false
  },
  {
    "dataType": "genestack:transcriptomicsParent",
    "isRequired": false,
    "metainfoType": "com.genestack.api.metainfo.StringValue",
    "name": "Genome Version",
    "isReadOnly": false
  },
  {
    "dataType": "genestack:transcriptomicsParent",
    "isRequired": false,
    "metainfoType": "com.genestack.api.metainfo.StringValue",
    "name": "Pipeline ID",
    "isReadOnly": false
  },
  {
    "dataType": "genestack:transcriptomicsParent",
    "isRequired": false,
    "metainfoType": "com.genestack.api.metainfo.ExternalLink",
    "name": "Data Files / Raw",
    "isReadOnly": false
  },
  {
    "dataType": "genestack:transcriptomicsParent",
    "isRequired": false,
    "metainfoType": "com.genestack.api.metainfo.ExternalLink",
    "name": "Data Files / Processed",
    "isReadOnly": false
  },
  {
    "dataType": "genestack:transcriptomicsParent",
    "isRequired": false,
    "metainfoType": "com.genestack.api.metainfo.ExternalLink",
    "name": "Import Source URL",
    "isReadOnly": false
  },
  {
    "dictionaryName": "Data Species",
    "dataType": "genestack:transcriptomicsParent",
    "isRequired": false,
    "metainfoType": "com.genestack.api.metainfo.StringValue",
    "name": "Data Species",
    "isReadOnly": false
  },
  {
    "dataType": "genestack:transcriptomicsParent",
    "isRequired": false,
    "metainfoType": "com.genestack.api.metainfo.StringValue",
    "name": "Name",
    "isReadOnly": false
  },
  {
    "dictionaryName": "Sequencing Platforms",
    "dataType": "genestack:facsParent",
    "isRequired": false,
    "metainfoType": "com.genestack.api.metainfo.StringValue",
    "name": "Experimental Platform",
    "isReadOnly": false
  },
  {
    "dataType": "genestack:facsParent",
    "isRequired": false,
    "metainfoType": "com.genestack.api.metainfo.StringValue",
    "name": "Data Processing Method",
    "isReadOnly": false
  },
  {
    "dataType": "genestack:facsParent",
    "isRequired": false,
    "metainfoType": "com.genestack.api.metainfo.StringValue",
    "name": "Scale",
    "isReadOnly": false
  },
  {
    "dataType": "genestack:facsParent",
    "isRequired": false,
    "metainfoType": "com.genestack.api.metainfo.StringValue",
    "name": "Pipeline ID",
    "isReadOnly": false
  },
  {
    "dataType": "genestack:facsParent",
    "isRequired": false,
    "metainfoType": "com.genestack.api.metainfo.ExternalLink",
    "name": "Raw Data Files",
    "isReadOnly": false
  },
  {
    "dataType": "genestack:facsParent",
    "isRequired": false,
    "metainfoType": "com.genestack.api.metainfo.ExternalLink",
    "name": "Processed Data Files",
    "isReadOnly": false
  },
  {
    "dataType": "genestack:facsParent",
    "isRequired": false,
    "metainfoType": "com.genestack.api.metainfo.ExternalLink",
    "name": "Import Source URL",
    "isReadOnly": false
  },
  {
    "dataType": "genestack:facsParent",
    "isRequired": false,
    "metainfoType": "com.genestack.api.metainfo.StringValue",
    "name": "Name",
    "isReadOnly": false
  },
  {
    "dataType": "genestack:sampleObject",
    "isRequired": true,
    "metainfoType": "com.genestack.api.metainfo.StringValue",
    "name": "Sample Source ID",
    "isReadOnly": true,
    "description": "Unique identifier about the sample"
  },
  {
    "dataType": "genestack:sampleObject",
    "isRequired": false,
    "metainfoType": "com.genestack.api.metainfo.StringValue",
    "name": "Sample Name",
    "isReadOnly": false
  },
  {
    "dictionaryName": "NCBI Taxonomy",
    "dataType": "genestack:sampleObject",
    "isRequired": false,
    "metainfoType": "com.genestack.api.metainfo.StringValue",
    "name": "Organism",
    "isReadOnly": false
  },
  {
    "dictionaryName": "Sex",
    "dataType": "genestack:sampleObject",
    "isRequired": false,
    "metainfoType": "com.genestack.api.metainfo.StringValue",
    "name": "Sex",
    "isReadOnly": false
  },
  {
    "dictionaryName": "Disease Ontology Extended",
    "dataType": "genestack:sampleObject",
    "isRequired": false,
    "metainfoType": "com.genestack.api.metainfo.StringValue",
    "name": "Disease",
    "isReadOnly": false
  },
  {
    "dataType": "genestack:sampleObject",
    "isRequired": false,
    "metainfoType": "com.genestack.api.metainfo.DecimalValue",
    "name": "Age",
    "isReadOnly": false
  },
  {
    "dictionaryName": "Units - Time/Frequency",
    "dataType": "genestack:sampleObject",
    "isRequired": false,
    "metainfoType": "com.genestack.api.metainfo.StringValue",
    "name": "Age Unit",
    "isReadOnly": false
  },
  {
    "dictionaryName": "Uberon Anatomical Entities",
    "dataType": "genestack:sampleObject",
    "isRequired": false,
    "metainfoType": "com.genestack.api.metainfo.StringValue",
    "name": "Tissue",
    "isReadOnly": false
  },
  {
    "dictionaryName": "Cell Type",
    "dataType": "genestack:sampleObject",
    "isRequired": false,
    "metainfoType": "com.genestack.api.metainfo.StringValue",
    "name": "Cell Type",
    "isReadOnly": false
  },
  {
    "dictionaryName": "Cellosaurus Controlled Vocabulary",
    "dataType": "genestack:sampleObject",
    "isRequired": false,
    "metainfoType": "com.genestack.api.metainfo.StringValue",
    "name": "Cell Line",
    "isReadOnly": false
  },
  {
    "dictionaryName": "ChEBI Ontology",
    "dataType": "genestack:sampleObject",
    "isRequired": false,
    "metainfoType": "com.genestack.api.metainfo.StringValue",
    "name": "Compound Treatment / Compound",
    "isReadOnly": false
  },
  {
    "dataType": "genestack:sampleObject",
    "isRequired": false,
    "metainfoType": "com.genestack.api.metainfo.DecimalValue",
    "name": "Compound Treatment / Dose",
    "isReadOnly": false
  },
  {
    "dictionaryName": "Units - Dose/Mass/Volume",
    "dataType": "genestack:sampleObject",
    "isRequired": false,
    "metainfoType": "com.genestack.api.metainfo.StringValue",
    "name": "Compound Treatment / Dose Unit",
    "isReadOnly": false
  },
  {
    "dataType": "genestack:sampleObject",
    "isRequired": false,
    "metainfoType": "com.genestack.api.metainfo.ExternalLink",
    "name": "Data Files / Raw",
    "isReadOnly": false
  },
  {
    "dataType": "genestack:sampleObject",
    "isRequired": false,
    "metainfoType": "com.genestack.api.metainfo.ExternalLink",
    "name": "Data Files / Processed",
    "isReadOnly": false
  },
  {
    "dataType": "genestack:sampleObject",
    "isRequired": false,
    "metainfoType": "com.genestack.api.metainfo.ExternalLink",
    "name": "Import Source URL",
    "isReadOnly": false
  },
  {
    "dictionaryName": "Sequencing Platforms",
    "dataType": "genestack:genomicsParent",
    "isRequired": false,
    "metainfoType": "com.genestack.api.metainfo.StringValue",
    "name": "Experimental Platform",
    "isReadOnly": false
  },
  {
    "dataType": "genestack:genomicsParent",
    "isRequired": false,
    "metainfoType": "com.genestack.api.metainfo.StringValue",
    "name": "Data Processing Method",
    "isReadOnly": false
  },
  {
    "dataType": "genestack:genomicsParent",
    "isRequired": false,
    "metainfoType": "com.genestack.api.metainfo.StringValue",
    "name": "Scale",
    "isReadOnly": false
  },
  {
    "dataType": "genestack:genomicsParent",
